environment:
  nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - node --version
  - npm --version
  - choco install ffmpeg
  - choco install r.project -version 3.6.0
  - set RPATH=C:\Program Files\R\R-3.6.0\bin\x64
  - set PATH=%RPATH%;%PATH%
  - SET ENVINFO_DEBUG=trace
  - npm run build
  - node --unhandled-rejections=strict -r esm src/cli.js
  - node --unhandled-rejections=strict dist/cli.js
  - SET ENVINFO_DEBUG=""
  - npm test

build: off
